### ISSUE TITLE
How does programiz online sql editor support complex types like jsonb?

### ISSUE THREAD

**Issue by ryzencool** [GaganpreetKaurKalsi/SQL-Editor#1]
Hi, I am developing a website about online SQL editor, I looked up some similar projects, [programiz online SQL editor] (https://www.programiz.com/sql/online-compiler/) is the most completed, and your SQL editor is very similar, you implemented it with alasql, but it is not supporting PostgreSQL's jsonb, programiz online SQL editor support many complex types and doesn't post any request to backend service. I want to get your advice about the concept of the programiz online SQL editor, thank you very much.

**Comment by GaganpreetKaurKalsi** [comment]
Hi!
I am not sure how programiz is working things out. You can look out for alasql documentation. It is actually pretty great. I have built just the minimum stuff. We can use alasql to create Tables and for all other stuff as well.
